"""RFC 7807 Problem Details and normalized domain exceptions for TravelOps AI."""

from datetime import UTC, datetime
from typing import Any

from fastapi import Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.core.context import get_correlation_id
from app.core.logging import logger


class InvalidParam(BaseModel):
    """Parameter-level error detail for validation failures."""

    field: str
    message: str
    error_type: str | None = None
    input_value: Any | None = None


class ProblemDetail(BaseModel):
    """RFC 7807 compliant problem details schema."""

    type: str = Field(
        default="https://travelops.ai/errors/general-error",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(
        default="An error occurred",
        description="A short, human-readable summary of the problem type.",
    )
    status: int = Field(
        default=400,
        description="The HTTP status code generated by the origin server.",
    )
    detail: str = Field(
        default="",
        description="A human-readable explanation specific to this occurrence of the problem.",
    )
    instance: str = Field(
        default="",
        description="A URI reference that identifies the specific occurrence of the problem.",
    )
    correlation_id: str = Field(
        default="",
        description="Distributed request tracing correlation ID.",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="UTC timestamp when the error occurred.",
    )
    invalid_params: list[InvalidParam] | None = Field(
        default=None,
        description="List of invalid fields when status is 422.",
    )


class AppException(Exception):
    """Base application exception for standardized error reporting."""

    def __init__(
        self,
        detail: str,
        status_code: int = status.HTTP_400_BAD_REQUEST,
        title: str = "Bad Request",
        error_type: str = "https://travelops.ai/errors/bad-request",
        invalid_params: list[InvalidParam] | None = None,
    ) -> None:
        super().__init__(detail)
        self.detail = detail
        self.status_code = status_code
        self.title = title
        self.error_type = error_type
        self.invalid_params = invalid_params


class NotFoundError(AppException):
    """Entity or resource not found error (HTTP 404)."""

    def __init__(self, detail: str = "Requested resource was not found") -> None:
        super().__init__(
            detail=detail,
            status_code=status.HTTP_404_NOT_FOUND,
            title="Resource Not Found",
            error_type="https://travelops.ai/errors/not-found",
        )


class ConflictError(AppException):
    """Resource conflict or duplicate error (HTTP 409)."""

    def __init__(self, detail: str = "Resource already exists or is in conflict") -> None:
        super().__init__(
            detail=detail,
            status_code=status.HTTP_409_CONFLICT,
            title="Conflict",
            error_type="https://travelops.ai/errors/conflict",
        )


class RateLimitExceededError(AppException):
    """Rate limit exceeded error (HTTP 429)."""

    def __init__(
        self,
        detail: str = "Too many requests. Please wait before retrying.",
        retry_after_seconds: int = 60,
    ) -> None:
        super().__init__(
            detail=detail,
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            title="Rate Limit Exceeded",
            error_type="https://travelops.ai/errors/rate-limit-exceeded",
        )
        self.retry_after_seconds = retry_after_seconds


class UnauthorizedError(AppException):
    """Authentication required or failed (HTTP 401)."""

    def __init__(self, detail: str = "Authentication credentials were invalid or missing") -> None:
        super().__init__(
            detail=detail,
            status_code=status.HTTP_401_UNAUTHORIZED,
            title="Unauthorized",
            error_type="https://travelops.ai/errors/unauthorized",
        )


class ForbiddenError(AppException):
    """Access forbidden due to permissions (HTTP 403)."""

    def __init__(self, detail: str = "You do not have permission to access this resource") -> None:
        super().__init__(
            detail=detail,
            status_code=status.HTTP_403_FORBIDDEN,
            title="Forbidden",
            error_type="https://travelops.ai/errors/forbidden",
        )


class ProviderUnavailableError(AppException):
    """External travel supplier or provider API failure (HTTP 503)."""

    def __init__(self, detail: str = "External travel provider is currently unavailable") -> None:
        super().__init__(
            detail=detail,
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            title="Provider Unavailable",
            error_type="https://travelops.ai/errors/provider-unavailable",
        )


async def app_exception_handler(request: Request, exc: AppException) -> JSONResponse:
    """Exception handler for custom domain AppException instances."""
    cid = getattr(request.state, "correlation_id", get_correlation_id() or "")
    problem = ProblemDetail(
        type=exc.error_type,
        title=exc.title,
        status=exc.status_code,
        detail=exc.detail,
        instance=request.url.path,
        correlation_id=cid,
        invalid_params=exc.invalid_params,
    )
    headers = {"X-Correlation-ID": cid, "X-Request-ID": cid}
    if isinstance(exc, RateLimitExceededError):
        headers["Retry-After"] = str(exc.retry_after_seconds)

    return JSONResponse(
        status_code=exc.status_code,
        content=problem.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers=headers,
    )


async def validation_exception_handler(
    request: Request, exc: RequestValidationError
) -> JSONResponse:
    """Exception handler translating FastAPI RequestValidationError into RFC 7807 Problem Details."""
    cid = getattr(request.state, "correlation_id", get_correlation_id() or "")
    invalid_params: list[InvalidParam] = []

    for err in exc.errors():
        loc = " -> ".join(str(item) for item in err.get("loc", []))
        msg = err.get("msg", "Validation failed")
        err_type = err.get("type")
        input_val = err.get("input")
        # Ensure input_val is serializable
        if not isinstance(input_val, (str, int, float, bool, list, dict, type(None))):
            input_val = str(input_val)

        invalid_params.append(
            InvalidParam(
                field=loc,
                message=msg,
                error_type=err_type,
                input_value=input_val,
            )
        )

    problem = ProblemDetail(
        type="https://travelops.ai/errors/validation-error",
        title="Unprocessable Entity",
        status=status.HTTP_422_UNPROCESSABLE_ENTITY,
        detail="One or more request parameters failed validation.",
        instance=request.url.path,
        correlation_id=cid,
        invalid_params=invalid_params,
    )

    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content=problem.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers={"X-Correlation-ID": cid, "X-Request-ID": cid},
    )


async def http_exception_handler(request: Request, exc: StarletteHTTPException) -> JSONResponse:
    """Exception handler translating Starlette/FastAPI HTTPExceptions into RFC 7807 Problem Details."""
    cid = getattr(request.state, "correlation_id", get_correlation_id() or "")
    titles = {
        400: "Bad Request",
        401: "Unauthorized",
        403: "Forbidden",
        404: "Resource Not Found",
        405: "Method Not Allowed",
        408: "Request Timeout",
        409: "Conflict",
        422: "Unprocessable Entity",
        429: "Too Many Requests",
        500: "Internal Server Error",
        502: "Bad Gateway",
        503: "Service Unavailable",
    }
    title = titles.get(exc.status_code, "HTTP Error")
    detail = str(exc.detail) if exc.detail else title

    problem = ProblemDetail(
        type=f"https://travelops.ai/errors/http-{exc.status_code}",
        title=title,
        status=exc.status_code,
        detail=detail,
        instance=request.url.path,
        correlation_id=cid,
    )

    return JSONResponse(
        status_code=exc.status_code,
        content=problem.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers={"X-Correlation-ID": cid, "X-Request-ID": cid},
    )


async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Global catch-all exception handler protecting against stack trace leaks."""
    cid = getattr(request.state, "correlation_id", get_correlation_id() or "")
    logger.error(
        f"Unhandled application exception on {request.method} {request.url.path} (cid={cid}): {exc}",
        exc_info=True,
    )

    problem = ProblemDetail(
        type="https://travelops.ai/errors/internal-server-error",
        title="Internal Server Error",
        status=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail="An internal server error occurred. Please contact system administrator with the correlation ID.",
        instance=request.url.path,
        correlation_id=cid,
    )

    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=problem.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers={"X-Correlation-ID": cid, "X-Request-ID": cid},
    )
